//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCVP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosicaoGPS
    {
        public int PGPS_ID { get; set; }
        public string VEIC { get; set; }
        public string LAT { get; set; }
        public string LON { get; set; }
        public Nullable<System.DateTime> DTHR { get; set; }
        public string COD_LINHA { get; set; }
    }
}
