//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCVP
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFCVP")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}
namespace WCFCVP.DAL
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PosicaoGPS", Namespace="http://schemas.datacontract.org/2004/07/WCFCVP.DAL")]
    public partial class PosicaoGPS : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string COD_LINHAField;
        
        private System.Nullable<System.DateTime> DTHRField;
        
        private string LATField;
        
        private string LONField;
        
        private int PGPS_IDField;
        
        private string VEICField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_LINHA
        {
            get
            {
                return this.COD_LINHAField;
            }
            set
            {
                this.COD_LINHAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DTHR
        {
            get
            {
                return this.DTHRField;
            }
            set
            {
                this.DTHRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LAT
        {
            get
            {
                return this.LATField;
            }
            set
            {
                this.LATField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LON
        {
            get
            {
                return this.LONField;
            }
            set
            {
                this.LONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PGPS_ID
        {
            get
            {
                return this.PGPS_IDField;
            }
            set
            {
                this.PGPS_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VEIC
        {
            get
            {
                return this.VEICField;
            }
            set
            {
                this.VEICField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService")]
public interface IService
{
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
    //string GetData(int value);
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
    //System.Threading.Tasks.Task<string> GetDataAsync(int value);
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
    //WCFCVP.CompositeType GetDataUsingDataContract(WCFCVP.CompositeType composite);
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
    //System.Threading.Tasks.Task<WCFCVP.CompositeType> GetDataUsingDataContractAsync(WCFCVP.CompositeType composite);
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBusLocalization", ReplyAction="http://tempuri.org/IService/GetBusLocalizationResponse")]
    //WCFCVP.DAL.PosicaoGPS[] GetBusLocalization(string busID, System.DateTime dateTime);
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBusLocalization", ReplyAction="http://tempuri.org/IService/GetBusLocalizationResponse")]
    //System.Threading.Tasks.Task<WCFCVP.DAL.PosicaoGPS[]> GetBusLocalizationAsync(string busID, System.DateTime dateTime);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    //public string GetData(int value)
    //{
    //    return base.Channel.GetData(value);
    //}
    
    //public System.Threading.Tasks.Task<string> GetDataAsync(int value)
    //{
    //    return base.Channel.GetDataAsync(value);
    //}
    
    //public WCFCVP.CompositeType GetDataUsingDataContract(WCFCVP.CompositeType composite)
    //{
    //    return base.Channel.GetDataUsingDataContract(composite);
    //}
    
    //public System.Threading.Tasks.Task<WCFCVP.CompositeType> GetDataUsingDataContractAsync(WCFCVP.CompositeType composite)
    //{
    //    return base.Channel.GetDataUsingDataContractAsync(composite);
    //}
    
    //public WCFCVP.DAL.PosicaoGPS[] GetBusLocalization(string busID, System.DateTime dateTime)
    //{
    //    return base.Channel.GetBusLocalization(busID, dateTime);
    //}
    
    //public System.Threading.Tasks.Task<WCFCVP.DAL.PosicaoGPS[]> GetBusLocalizationAsync(string busID, System.DateTime dateTime)
    //{
    //    return base.Channel.GetBusLocalizationAsync(busID, dateTime);
    //}
}
